In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import difflib 
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.metrics.pairwise import cosine_similarity  

In [2]:
data = pd.read_csv('movies.csv')
data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [3]:
selected_features = ['genres', 'keywords', 'cast', 'director', 'tagline', 'spoken_languages']
for i in selected_features: 
    data[i] = data[i].fillna('')

In [4]:
combine = data['genres'] + ' ' + data['keywords'] + ' ' + data['cast'] + ' ' + data['director'] + ' ' + data['tagline'] + ' ' + data['spoken_languages']
print(combine)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  Edward Burns Kerry Bish\u00e9 ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      Daniel Henney Eliza Coupe Bill Paxton Alan R...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [5]:
vectorizer = TfidfVectorizer()
feature_vector = vectorizer.fit_transform(combine)
print(feature_vector)

  (0, 16038)	0.11439570003427277
  (0, 5042)	0.11439570003427277
  (0, 5032)	0.11439570003427277
  (0, 4955)	0.03382535004447686
  (0, 10828)	0.06445816090212846
  (0, 4928)	0.03382535004447686
  (0, 7699)	0.06445816090212846
  (0, 11557)	0.2652429833464349
  (0, 11245)	0.08820849062413907
  (0, 17185)	0.12497561131298904
  (0, 15337)	0.06916683023277362
  (0, 4967)	0.23419264929303912
  (0, 2443)	0.16836329692063867
  (0, 7796)	0.10995558747551541
  (0, 13084)	0.18933226900260217
  (0, 10276)	0.156532471800267
  (0, 8801)	0.22135674843150127
  (0, 14679)	0.14768159042461354
  (0, 16853)	0.19342275408321374
  (0, 14129)	0.2007609503375522
  (0, 13381)	0.21224953183557232
  (0, 17480)	0.19687970082852738
  (0, 17194)	0.23046396502743027
  (0, 13411)	0.1464201794631719
  (0, 14339)	0.20852084756996345
  :	:
  (4801, 3813)	0.33342031383493365
  (4801, 4955)	0.03671047398502014
  (4801, 10828)	0.034978051015117397
  (4801, 4928)	0.03671047398502014
  (4801, 7699)	0.034978051015117397
  (48

In [6]:
similarity = cosine_similarity(feature_vector)
print(similarity)

[[1.         0.0760085  0.09322493 ... 0.00675709 0.00699273 0.00658849]
 [0.0760085  1.         0.04073079 ... 0.03969966 0.00423514 0.00399031]
 [0.09322493 0.04073079 1.         ... 0.01272804 0.06221124 0.01241047]
 ...
 [0.00675709 0.03969966 0.01272804 ... 1.         0.00496896 0.03107255]
 [0.00699273 0.00423514 0.06221124 ... 0.00496896 1.         0.00484498]
 [0.00658849 0.00399031 0.01241047 ... 0.03107255 0.00484498 1.        ]]


In [7]:
name = input('name your favourite movie name: ')

name your favourite movie name: Avatar


In [10]:
title = data['title'].tolist()
find = difflib.get_close_matches(name, title)
print(find)

['Avatar']


In [11]:
close_match = find[0]

In [12]:
index = data[data.title == close_match]['index'].values[0]
print(index)

0


In [13]:
 similarity_score = list(enumerate(similarity[index]))
print(similarity_score)

[(0, 1.0000000000000002), (1, 0.07600849959681513), (2, 0.09322492595013447), (3, 0.019528839027713844), (4, 0.11051966293128349), (5, 0.08502616688094267), (6, 0.014685133509076895), (7, 0.04179669584966409), (8, 0.035601874843818174), (9, 0.0320704485993822), (10, 0.10179905350540602), (11, 0.06445098609853656), (12, 0.034751780769473856), (13, 0.03484881069050067), (14, 0.07381296165255233), (15, 0.0253159562343544), (16, 0.03964147146124955), (17, 0.07352088409467843), (18, 0.06189049295720054), (19, 0.04362412036935307), (20, 0.045191878336508555), (21, 0.018603428604699292), (22, 0.03557354860460124), (23, 0.055355852419434484), (24, 0.05120381548872366), (25, 0.058310778296162394), (26, 0.07302470877222401), (27, 0.04049133584276953), (28, 0.04631381869638433), (29, 0.04441661140027114), (30, 0.08115198592305585), (31, 0.06537747645958256), (32, 0.03564177083670149), (33, 0.04153819930181904), (34, 0.0066884065736518075), (35, 0.08808097246476108), (36, 0.053897783626359407), (3

In [14]:
len(similarity_score)

4803

In [15]:
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies )

[(0, 1.0000000000000002), (3158, 0.2826880874002935), (2403, 0.24875050315326783), (94, 0.24476731830396253), (56, 0.20545686686941436), (47, 0.20282236581084992), (1053, 0.1983658884063908), (2229, 0.18456076350651918), (838, 0.1820868017474801), (4593, 0.17600613420911318), (239, 0.17561722574251173), (4401, 0.17555870546862473), (3730, 0.17454007096963053), (1531, 0.1705433769366178), (2696, 0.1667086874014174), (1873, 0.16417340392968893), (812, 0.16263136312401738), (643, 0.15860462402059053), (1245, 0.15770235933481616), (2198, 0.15486187410164912), (770, 0.151887987518582), (1922, 0.1481768303911511), (342, 0.14699209302349675), (1178, 0.1465202348787592), (206, 0.14447710163675948), (1914, 0.14395079582370846), (3208, 0.14312507712084518), (1951, 0.14053248745892946), (43, 0.13957495526687363), (1473, 0.1373577893368955), (2803, 0.13593906888189045), (158, 0.1358094030287536), (278, 0.13512729516357255), (1759, 0.13375402216250548), (1650, 0.13249384640165837), (3815, 0.1307965

In [16]:
print('movies suggested for you: \n')

i = 1
for movies in sorted_similar_movies:
    index = movies[0]
    title_from_movies = data[data.index==index]['title'].values[0]
    if(i<11):
        print(i, '.', title_from_movies)
        i+=1

movies suggested for you: 

1 . Avatar
2 . Alien
3 . Aliens
4 . Guardians of the Galaxy
5 . Star Trek Beyond
6 . Star Trek Into Darkness
7 . Galaxy Quest
8 . Machete Kills
9 . Alien³
10 . Trekkies
